In [2]:
import numpy as np
A=[[1,2,3],[4,5,6],[7,8,9]]
print(np.array(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = complex)
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [7]:
import numpy as np
A = np.zeros((3,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np
A = np.ones((3,3),dtype = int)
print(A)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
import numpy as np
A = np.identity(3,dtype = int)
print(A)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
import numpy as np
A=[[1,2,3,10],[4,5,6,20],[7,8,9,30]]
print(np.array(A))
print(A[2][2])
print(A[:,1])


[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]
9


TypeError: list indices must be integers or slices, not tuple

In [26]:
a=[1,2,3,4,5]
b=[2,3,4,5,6]

sum = []
for i in range(len(a)):
        sum.append(a[i]+b[i])
print(sum)

[3, 5, 7, 9, 11]


In [28]:
print(a+b)


[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]


In [30]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])
print(a+b)

[ 3  5  7  9 11]


In [32]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])
print(a-b)

[-1 -1 -1 -1 -1]


In [34]:
a=np.array([1,2,3,4,5])
print(2*a)

[ 2  4  6  8 10]


In [37]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])
print(a.dot(b))

70


In [39]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])
print(np.outer(a,b))
print(np.outer(b,a))

[[ 2  3  4  5  6]
 [ 4  6  8 10 12]
 [ 6  9 12 15 18]
 [ 8 12 16 20 24]
 [10 15 20 25 30]]
[[ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]]
